/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/auth/verify-email/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthRenewPasswordIndexRouteImport } from './routes/auth/renew-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as AuthenticatedDashboardLayoutRouteImport } from './routes/_authenticated.dashboard/_layout'
import { Route as AuthenticatedDashboardLayoutIndexRouteImport } from './routes/_authenticated.dashboard/_layout/index'
import { Route as AuthenticatedDashboardTenantsCreateRouteImport } from './routes/_authenticated.dashboard/tenants/create'
import { Route as AuthenticatedDashboardKnowledgeBaseCreateRouteImport } from './routes/_authenticated.dashboard/knowledge-base/create'
import { Route as AuthenticatedDashboardChatbotsDemoRouteImport } from './routes/_authenticated.dashboard/chatbots/demo'
import { Route as AuthenticatedDashboardChatbotsCreateRouteImport } from './routes/_authenticated.dashboard/chatbots/create'
import { Route as AuthenticatedDashboardChatbotsIdRouteImport } from './routes/_authenticated.dashboard/chatbots/$id'
import { Route as AuthenticatedDashboardLayoutUsagesRouteImport } from './routes/_authenticated.dashboard/_layout/usages'
import { Route as AuthenticatedDashboardLayoutKnowledgeBaseRouteImport } from './routes/_authenticated.dashboard/_layout/knowledge-base'
import { Route as AuthenticatedDashboardLayoutChatbotsRouteImport } from './routes/_authenticated.dashboard/_layout/chatbots'
import { Route as AuthenticatedDashboardKnowledgeBaseCreateIndexRouteImport } from './routes/_authenticated.dashboard/knowledge-base/create/index'
import { Route as AuthenticatedDashboardChatbotsCreateIndexRouteImport } from './routes/_authenticated.dashboard/chatbots/create/index'
import { Route as AuthenticatedDashboardChatbotsIdIndexRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/index'
import { Route as AuthenticatedDashboardKnowledgeBaseCreateWebsitesRouteImport } from './routes/_authenticated.dashboard/knowledge-base/create/websites'
import { Route as AuthenticatedDashboardKnowledgeBaseCreateTextRouteImport } from './routes/_authenticated.dashboard/knowledge-base/create/text'
import { Route as AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRouteImport } from './routes/_authenticated.dashboard/knowledge-base/create/knowledge'
import { Route as AuthenticatedDashboardKnowledgeBaseCreateFilesRouteImport } from './routes/_authenticated.dashboard/knowledge-base/create/files'
import { Route as AuthenticatedDashboardChatbotsCreateWebsitesRouteImport } from './routes/_authenticated.dashboard/chatbots/create/websites'
import { Route as AuthenticatedDashboardChatbotsCreateTextRouteImport } from './routes/_authenticated.dashboard/chatbots/create/text'
import { Route as AuthenticatedDashboardChatbotsCreateKnowledgeRouteImport } from './routes/_authenticated.dashboard/chatbots/create/knowledge'
import { Route as AuthenticatedDashboardChatbotsCreateFilesRouteImport } from './routes/_authenticated.dashboard/chatbots/create/files'
import { Route as AuthenticatedDashboardChatbotsIdWidgetRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/widget'
import { Route as AuthenticatedDashboardChatbotsIdSettingsRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/settings'
import { Route as AuthenticatedDashboardChatbotsIdPlaygroundRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/playground'
import { Route as AuthenticatedDashboardLayoutSettingsSecurityRouteImport } from './routes/_authenticated.dashboard/_layout/settings/security'
import { Route as AuthenticatedDashboardLayoutSettingsPlansRouteImport } from './routes/_authenticated.dashboard/_layout/settings/plans'
import { Route as AuthenticatedDashboardLayoutSettingsMembersRouteImport } from './routes/_authenticated.dashboard/_layout/settings/members'
import { Route as AuthenticatedDashboardLayoutSettingsGeneralRouteImport } from './routes/_authenticated.dashboard/_layout/settings/general'
import { Route as AuthenticatedDashboardLayoutSettingsBillingRouteImport } from './routes/_authenticated.dashboard/_layout/settings/billing'
import { Route as AuthenticatedDashboardChatbotsIdSourcesIndexRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/sources/index'
import { Route as AuthenticatedDashboardChatbotsIdSettingsIndexRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/settings/index'
import { Route as AuthenticatedDashboardChatbotsIdSourcesWebsitesRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/sources/websites'
import { Route as AuthenticatedDashboardChatbotsIdSourcesTextRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/sources/text'
import { Route as AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/sources/knowledge-bases'
import { Route as AuthenticatedDashboardChatbotsIdSourcesFilesRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/sources/files'
import { Route as AuthenticatedDashboardChatbotsIdSettingsSecurityRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/settings/security'
import { Route as AuthenticatedDashboardChatbotsIdSettingsGeneralRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/settings/general'
import { Route as AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/settings/chat-interface'
import { Route as AuthenticatedDashboardChatbotsIdSettingsAiRouteImport } from './routes/_authenticated.dashboard/chatbots/$id/settings/ai'

const AuthenticatedDashboardRouteImport = createFileRoute(
  '/_authenticated/dashboard',
)()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/auth/verify-email/',
  path: '/auth/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRenewPasswordIndexRoute = AuthRenewPasswordIndexRouteImport.update({
  id: '/auth/renew-password/',
  path: '/auth/renew-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardLayoutRoute =
  AuthenticatedDashboardLayoutRouteImport.update({
    id: '/_layout',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLayoutIndexRoute =
  AuthenticatedDashboardLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardTenantsCreateRoute =
  AuthenticatedDashboardTenantsCreateRouteImport.update({
    id: '/tenants/create',
    path: '/tenants/create',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKnowledgeBaseCreateRoute =
  AuthenticatedDashboardKnowledgeBaseCreateRouteImport.update({
    id: '/knowledge-base/create',
    path: '/knowledge-base/create',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChatbotsDemoRoute =
  AuthenticatedDashboardChatbotsDemoRouteImport.update({
    id: '/chatbots/demo',
    path: '/chatbots/demo',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChatbotsCreateRoute =
  AuthenticatedDashboardChatbotsCreateRouteImport.update({
    id: '/chatbots/create',
    path: '/chatbots/create',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdRoute =
  AuthenticatedDashboardChatbotsIdRouteImport.update({
    id: '/chatbots/$id',
    path: '/chatbots/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLayoutUsagesRoute =
  AuthenticatedDashboardLayoutUsagesRouteImport.update({
    id: '/usages',
    path: '/usages',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutKnowledgeBaseRoute =
  AuthenticatedDashboardLayoutKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutChatbotsRoute =
  AuthenticatedDashboardLayoutChatbotsRouteImport.update({
    id: '/chatbots',
    path: '/chatbots',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardKnowledgeBaseCreateIndexRoute =
  AuthenticatedDashboardKnowledgeBaseCreateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardKnowledgeBaseCreateRoute,
  } as any)
const AuthenticatedDashboardChatbotsCreateIndexRoute =
  AuthenticatedDashboardChatbotsCreateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardChatbotsCreateRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdIndexRoute =
  AuthenticatedDashboardChatbotsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdRoute,
  } as any)
const AuthenticatedDashboardKnowledgeBaseCreateWebsitesRoute =
  AuthenticatedDashboardKnowledgeBaseCreateWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => AuthenticatedDashboardKnowledgeBaseCreateRoute,
  } as any)
const AuthenticatedDashboardKnowledgeBaseCreateTextRoute =
  AuthenticatedDashboardKnowledgeBaseCreateTextRouteImport.update({
    id: '/text',
    path: '/text',
    getParentRoute: () => AuthenticatedDashboardKnowledgeBaseCreateRoute,
  } as any)
const AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRoute =
  AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedDashboardKnowledgeBaseCreateRoute,
  } as any)
const AuthenticatedDashboardKnowledgeBaseCreateFilesRoute =
  AuthenticatedDashboardKnowledgeBaseCreateFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedDashboardKnowledgeBaseCreateRoute,
  } as any)
const AuthenticatedDashboardChatbotsCreateWebsitesRoute =
  AuthenticatedDashboardChatbotsCreateWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => AuthenticatedDashboardChatbotsCreateRoute,
  } as any)
const AuthenticatedDashboardChatbotsCreateTextRoute =
  AuthenticatedDashboardChatbotsCreateTextRouteImport.update({
    id: '/text',
    path: '/text',
    getParentRoute: () => AuthenticatedDashboardChatbotsCreateRoute,
  } as any)
const AuthenticatedDashboardChatbotsCreateKnowledgeRoute =
  AuthenticatedDashboardChatbotsCreateKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedDashboardChatbotsCreateRoute,
  } as any)
const AuthenticatedDashboardChatbotsCreateFilesRoute =
  AuthenticatedDashboardChatbotsCreateFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedDashboardChatbotsCreateRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdWidgetRoute =
  AuthenticatedDashboardChatbotsIdWidgetRouteImport.update({
    id: '/widget',
    path: '/widget',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSettingsRoute =
  AuthenticatedDashboardChatbotsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdPlaygroundRoute =
  AuthenticatedDashboardChatbotsIdPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdRoute,
  } as any)
const AuthenticatedDashboardLayoutSettingsSecurityRoute =
  AuthenticatedDashboardLayoutSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutSettingsPlansRoute =
  AuthenticatedDashboardLayoutSettingsPlansRouteImport.update({
    id: '/settings/plans',
    path: '/settings/plans',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutSettingsMembersRoute =
  AuthenticatedDashboardLayoutSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutSettingsGeneralRoute =
  AuthenticatedDashboardLayoutSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardLayoutSettingsBillingRoute =
  AuthenticatedDashboardLayoutSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => AuthenticatedDashboardLayoutRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSourcesIndexRoute =
  AuthenticatedDashboardChatbotsIdSourcesIndexRouteImport.update({
    id: '/sources/',
    path: '/sources/',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSettingsIndexRoute =
  AuthenticatedDashboardChatbotsIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdSettingsRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSourcesWebsitesRoute =
  AuthenticatedDashboardChatbotsIdSourcesWebsitesRouteImport.update({
    id: '/sources/websites',
    path: '/sources/websites',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSourcesTextRoute =
  AuthenticatedDashboardChatbotsIdSourcesTextRouteImport.update({
    id: '/sources/text',
    path: '/sources/text',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRoute =
  AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRouteImport.update({
    id: '/sources/knowledge-bases',
    path: '/sources/knowledge-bases',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSourcesFilesRoute =
  AuthenticatedDashboardChatbotsIdSourcesFilesRouteImport.update({
    id: '/sources/files',
    path: '/sources/files',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSettingsSecurityRoute =
  AuthenticatedDashboardChatbotsIdSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdSettingsRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSettingsGeneralRoute =
  AuthenticatedDashboardChatbotsIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdSettingsRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRoute =
  AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRouteImport.update({
    id: '/chat-interface',
    path: '/chat-interface',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdSettingsRoute,
  } as any)
const AuthenticatedDashboardChatbotsIdSettingsAiRoute =
  AuthenticatedDashboardChatbotsIdSettingsAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => AuthenticatedDashboardChatbotsIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/renew-password': typeof AuthRenewPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/dashboard/chatbots': typeof AuthenticatedDashboardLayoutChatbotsRoute
  '/dashboard/knowledge-base': typeof AuthenticatedDashboardLayoutKnowledgeBaseRoute
  '/dashboard/usages': typeof AuthenticatedDashboardLayoutUsagesRoute
  '/dashboard/chatbots/$id': typeof AuthenticatedDashboardChatbotsIdRouteWithChildren
  '/dashboard/chatbots/create': typeof AuthenticatedDashboardChatbotsCreateRouteWithChildren
  '/dashboard/chatbots/demo': typeof AuthenticatedDashboardChatbotsDemoRoute
  '/dashboard/knowledge-base/create': typeof AuthenticatedDashboardKnowledgeBaseCreateRouteWithChildren
  '/dashboard/tenants/create': typeof AuthenticatedDashboardTenantsCreateRoute
  '/dashboard/': typeof AuthenticatedDashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof AuthenticatedDashboardLayoutSettingsBillingRoute
  '/dashboard/settings/general': typeof AuthenticatedDashboardLayoutSettingsGeneralRoute
  '/dashboard/settings/members': typeof AuthenticatedDashboardLayoutSettingsMembersRoute
  '/dashboard/settings/plans': typeof AuthenticatedDashboardLayoutSettingsPlansRoute
  '/dashboard/settings/security': typeof AuthenticatedDashboardLayoutSettingsSecurityRoute
  '/dashboard/chatbots/$id/playground': typeof AuthenticatedDashboardChatbotsIdPlaygroundRoute
  '/dashboard/chatbots/$id/settings': typeof AuthenticatedDashboardChatbotsIdSettingsRouteWithChildren
  '/dashboard/chatbots/$id/widget': typeof AuthenticatedDashboardChatbotsIdWidgetRoute
  '/dashboard/chatbots/create/files': typeof AuthenticatedDashboardChatbotsCreateFilesRoute
  '/dashboard/chatbots/create/knowledge': typeof AuthenticatedDashboardChatbotsCreateKnowledgeRoute
  '/dashboard/chatbots/create/text': typeof AuthenticatedDashboardChatbotsCreateTextRoute
  '/dashboard/chatbots/create/websites': typeof AuthenticatedDashboardChatbotsCreateWebsitesRoute
  '/dashboard/knowledge-base/create/files': typeof AuthenticatedDashboardKnowledgeBaseCreateFilesRoute
  '/dashboard/knowledge-base/create/knowledge': typeof AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRoute
  '/dashboard/knowledge-base/create/text': typeof AuthenticatedDashboardKnowledgeBaseCreateTextRoute
  '/dashboard/knowledge-base/create/websites': typeof AuthenticatedDashboardKnowledgeBaseCreateWebsitesRoute
  '/dashboard/chatbots/$id/': typeof AuthenticatedDashboardChatbotsIdIndexRoute
  '/dashboard/chatbots/create/': typeof AuthenticatedDashboardChatbotsCreateIndexRoute
  '/dashboard/knowledge-base/create/': typeof AuthenticatedDashboardKnowledgeBaseCreateIndexRoute
  '/dashboard/chatbots/$id/settings/ai': typeof AuthenticatedDashboardChatbotsIdSettingsAiRoute
  '/dashboard/chatbots/$id/settings/chat-interface': typeof AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRoute
  '/dashboard/chatbots/$id/settings/general': typeof AuthenticatedDashboardChatbotsIdSettingsGeneralRoute
  '/dashboard/chatbots/$id/settings/security': typeof AuthenticatedDashboardChatbotsIdSettingsSecurityRoute
  '/dashboard/chatbots/$id/sources/files': typeof AuthenticatedDashboardChatbotsIdSourcesFilesRoute
  '/dashboard/chatbots/$id/sources/knowledge-bases': typeof AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRoute
  '/dashboard/chatbots/$id/sources/text': typeof AuthenticatedDashboardChatbotsIdSourcesTextRoute
  '/dashboard/chatbots/$id/sources/websites': typeof AuthenticatedDashboardChatbotsIdSourcesWebsitesRoute
  '/dashboard/chatbots/$id/settings/': typeof AuthenticatedDashboardChatbotsIdSettingsIndexRoute
  '/dashboard/chatbots/$id/sources': typeof AuthenticatedDashboardChatbotsIdSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardLayoutIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/renew-password': typeof AuthRenewPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/dashboard/chatbots': typeof AuthenticatedDashboardLayoutChatbotsRoute
  '/dashboard/knowledge-base': typeof AuthenticatedDashboardLayoutKnowledgeBaseRoute
  '/dashboard/usages': typeof AuthenticatedDashboardLayoutUsagesRoute
  '/dashboard/chatbots/demo': typeof AuthenticatedDashboardChatbotsDemoRoute
  '/dashboard/tenants/create': typeof AuthenticatedDashboardTenantsCreateRoute
  '/dashboard/settings/billing': typeof AuthenticatedDashboardLayoutSettingsBillingRoute
  '/dashboard/settings/general': typeof AuthenticatedDashboardLayoutSettingsGeneralRoute
  '/dashboard/settings/members': typeof AuthenticatedDashboardLayoutSettingsMembersRoute
  '/dashboard/settings/plans': typeof AuthenticatedDashboardLayoutSettingsPlansRoute
  '/dashboard/settings/security': typeof AuthenticatedDashboardLayoutSettingsSecurityRoute
  '/dashboard/chatbots/$id/playground': typeof AuthenticatedDashboardChatbotsIdPlaygroundRoute
  '/dashboard/chatbots/$id/widget': typeof AuthenticatedDashboardChatbotsIdWidgetRoute
  '/dashboard/chatbots/create/files': typeof AuthenticatedDashboardChatbotsCreateFilesRoute
  '/dashboard/chatbots/create/knowledge': typeof AuthenticatedDashboardChatbotsCreateKnowledgeRoute
  '/dashboard/chatbots/create/text': typeof AuthenticatedDashboardChatbotsCreateTextRoute
  '/dashboard/chatbots/create/websites': typeof AuthenticatedDashboardChatbotsCreateWebsitesRoute
  '/dashboard/knowledge-base/create/files': typeof AuthenticatedDashboardKnowledgeBaseCreateFilesRoute
  '/dashboard/knowledge-base/create/knowledge': typeof AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRoute
  '/dashboard/knowledge-base/create/text': typeof AuthenticatedDashboardKnowledgeBaseCreateTextRoute
  '/dashboard/knowledge-base/create/websites': typeof AuthenticatedDashboardKnowledgeBaseCreateWebsitesRoute
  '/dashboard/chatbots/$id': typeof AuthenticatedDashboardChatbotsIdIndexRoute
  '/dashboard/chatbots/create': typeof AuthenticatedDashboardChatbotsCreateIndexRoute
  '/dashboard/knowledge-base/create': typeof AuthenticatedDashboardKnowledgeBaseCreateIndexRoute
  '/dashboard/chatbots/$id/settings/ai': typeof AuthenticatedDashboardChatbotsIdSettingsAiRoute
  '/dashboard/chatbots/$id/settings/chat-interface': typeof AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRoute
  '/dashboard/chatbots/$id/settings/general': typeof AuthenticatedDashboardChatbotsIdSettingsGeneralRoute
  '/dashboard/chatbots/$id/settings/security': typeof AuthenticatedDashboardChatbotsIdSettingsSecurityRoute
  '/dashboard/chatbots/$id/sources/files': typeof AuthenticatedDashboardChatbotsIdSourcesFilesRoute
  '/dashboard/chatbots/$id/sources/knowledge-bases': typeof AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRoute
  '/dashboard/chatbots/$id/sources/text': typeof AuthenticatedDashboardChatbotsIdSourcesTextRoute
  '/dashboard/chatbots/$id/sources/websites': typeof AuthenticatedDashboardChatbotsIdSourcesWebsitesRoute
  '/dashboard/chatbots/$id/settings': typeof AuthenticatedDashboardChatbotsIdSettingsIndexRoute
  '/dashboard/chatbots/$id/sources': typeof AuthenticatedDashboardChatbotsIdSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/_layout': typeof AuthenticatedDashboardLayoutRouteWithChildren
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/renew-password/': typeof AuthRenewPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/_authenticated/dashboard/_layout/chatbots': typeof AuthenticatedDashboardLayoutChatbotsRoute
  '/_authenticated/dashboard/_layout/knowledge-base': typeof AuthenticatedDashboardLayoutKnowledgeBaseRoute
  '/_authenticated/dashboard/_layout/usages': typeof AuthenticatedDashboardLayoutUsagesRoute
  '/_authenticated/dashboard/chatbots/$id': typeof AuthenticatedDashboardChatbotsIdRouteWithChildren
  '/_authenticated/dashboard/chatbots/create': typeof AuthenticatedDashboardChatbotsCreateRouteWithChildren
  '/_authenticated/dashboard/chatbots/demo': typeof AuthenticatedDashboardChatbotsDemoRoute
  '/_authenticated/dashboard/knowledge-base/create': typeof AuthenticatedDashboardKnowledgeBaseCreateRouteWithChildren
  '/_authenticated/dashboard/tenants/create': typeof AuthenticatedDashboardTenantsCreateRoute
  '/_authenticated/dashboard/_layout/': typeof AuthenticatedDashboardLayoutIndexRoute
  '/_authenticated/dashboard/_layout/settings/billing': typeof AuthenticatedDashboardLayoutSettingsBillingRoute
  '/_authenticated/dashboard/_layout/settings/general': typeof AuthenticatedDashboardLayoutSettingsGeneralRoute
  '/_authenticated/dashboard/_layout/settings/members': typeof AuthenticatedDashboardLayoutSettingsMembersRoute
  '/_authenticated/dashboard/_layout/settings/plans': typeof AuthenticatedDashboardLayoutSettingsPlansRoute
  '/_authenticated/dashboard/_layout/settings/security': typeof AuthenticatedDashboardLayoutSettingsSecurityRoute
  '/_authenticated/dashboard/chatbots/$id/playground': typeof AuthenticatedDashboardChatbotsIdPlaygroundRoute
  '/_authenticated/dashboard/chatbots/$id/settings': typeof AuthenticatedDashboardChatbotsIdSettingsRouteWithChildren
  '/_authenticated/dashboard/chatbots/$id/widget': typeof AuthenticatedDashboardChatbotsIdWidgetRoute
  '/_authenticated/dashboard/chatbots/create/files': typeof AuthenticatedDashboardChatbotsCreateFilesRoute
  '/_authenticated/dashboard/chatbots/create/knowledge': typeof AuthenticatedDashboardChatbotsCreateKnowledgeRoute
  '/_authenticated/dashboard/chatbots/create/text': typeof AuthenticatedDashboardChatbotsCreateTextRoute
  '/_authenticated/dashboard/chatbots/create/websites': typeof AuthenticatedDashboardChatbotsCreateWebsitesRoute
  '/_authenticated/dashboard/knowledge-base/create/files': typeof AuthenticatedDashboardKnowledgeBaseCreateFilesRoute
  '/_authenticated/dashboard/knowledge-base/create/knowledge': typeof AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRoute
  '/_authenticated/dashboard/knowledge-base/create/text': typeof AuthenticatedDashboardKnowledgeBaseCreateTextRoute
  '/_authenticated/dashboard/knowledge-base/create/websites': typeof AuthenticatedDashboardKnowledgeBaseCreateWebsitesRoute
  '/_authenticated/dashboard/chatbots/$id/': typeof AuthenticatedDashboardChatbotsIdIndexRoute
  '/_authenticated/dashboard/chatbots/create/': typeof AuthenticatedDashboardChatbotsCreateIndexRoute
  '/_authenticated/dashboard/knowledge-base/create/': typeof AuthenticatedDashboardKnowledgeBaseCreateIndexRoute
  '/_authenticated/dashboard/chatbots/$id/settings/ai': typeof AuthenticatedDashboardChatbotsIdSettingsAiRoute
  '/_authenticated/dashboard/chatbots/$id/settings/chat-interface': typeof AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRoute
  '/_authenticated/dashboard/chatbots/$id/settings/general': typeof AuthenticatedDashboardChatbotsIdSettingsGeneralRoute
  '/_authenticated/dashboard/chatbots/$id/settings/security': typeof AuthenticatedDashboardChatbotsIdSettingsSecurityRoute
  '/_authenticated/dashboard/chatbots/$id/sources/files': typeof AuthenticatedDashboardChatbotsIdSourcesFilesRoute
  '/_authenticated/dashboard/chatbots/$id/sources/knowledge-bases': typeof AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRoute
  '/_authenticated/dashboard/chatbots/$id/sources/text': typeof AuthenticatedDashboardChatbotsIdSourcesTextRoute
  '/_authenticated/dashboard/chatbots/$id/sources/websites': typeof AuthenticatedDashboardChatbotsIdSourcesWebsitesRoute
  '/_authenticated/dashboard/chatbots/$id/settings/': typeof AuthenticatedDashboardChatbotsIdSettingsIndexRoute
  '/_authenticated/dashboard/chatbots/$id/sources/': typeof AuthenticatedDashboardChatbotsIdSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/auth/renew-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dashboard/chatbots'
    | '/dashboard/knowledge-base'
    | '/dashboard/usages'
    | '/dashboard/chatbots/$id'
    | '/dashboard/chatbots/create'
    | '/dashboard/chatbots/demo'
    | '/dashboard/knowledge-base/create'
    | '/dashboard/tenants/create'
    | '/dashboard/'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/settings/members'
    | '/dashboard/settings/plans'
    | '/dashboard/settings/security'
    | '/dashboard/chatbots/$id/playground'
    | '/dashboard/chatbots/$id/settings'
    | '/dashboard/chatbots/$id/widget'
    | '/dashboard/chatbots/create/files'
    | '/dashboard/chatbots/create/knowledge'
    | '/dashboard/chatbots/create/text'
    | '/dashboard/chatbots/create/websites'
    | '/dashboard/knowledge-base/create/files'
    | '/dashboard/knowledge-base/create/knowledge'
    | '/dashboard/knowledge-base/create/text'
    | '/dashboard/knowledge-base/create/websites'
    | '/dashboard/chatbots/$id/'
    | '/dashboard/chatbots/create/'
    | '/dashboard/knowledge-base/create/'
    | '/dashboard/chatbots/$id/settings/ai'
    | '/dashboard/chatbots/$id/settings/chat-interface'
    | '/dashboard/chatbots/$id/settings/general'
    | '/dashboard/chatbots/$id/settings/security'
    | '/dashboard/chatbots/$id/sources/files'
    | '/dashboard/chatbots/$id/sources/knowledge-bases'
    | '/dashboard/chatbots/$id/sources/text'
    | '/dashboard/chatbots/$id/sources/websites'
    | '/dashboard/chatbots/$id/settings/'
    | '/dashboard/chatbots/$id/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/auth/register'
    | '/auth/renew-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dashboard/chatbots'
    | '/dashboard/knowledge-base'
    | '/dashboard/usages'
    | '/dashboard/chatbots/demo'
    | '/dashboard/tenants/create'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/settings/members'
    | '/dashboard/settings/plans'
    | '/dashboard/settings/security'
    | '/dashboard/chatbots/$id/playground'
    | '/dashboard/chatbots/$id/widget'
    | '/dashboard/chatbots/create/files'
    | '/dashboard/chatbots/create/knowledge'
    | '/dashboard/chatbots/create/text'
    | '/dashboard/chatbots/create/websites'
    | '/dashboard/knowledge-base/create/files'
    | '/dashboard/knowledge-base/create/knowledge'
    | '/dashboard/knowledge-base/create/text'
    | '/dashboard/knowledge-base/create/websites'
    | '/dashboard/chatbots/$id'
    | '/dashboard/chatbots/create'
    | '/dashboard/knowledge-base/create'
    | '/dashboard/chatbots/$id/settings/ai'
    | '/dashboard/chatbots/$id/settings/chat-interface'
    | '/dashboard/chatbots/$id/settings/general'
    | '/dashboard/chatbots/$id/settings/security'
    | '/dashboard/chatbots/$id/sources/files'
    | '/dashboard/chatbots/$id/sources/knowledge-bases'
    | '/dashboard/chatbots/$id/sources/text'
    | '/dashboard/chatbots/$id/sources/websites'
    | '/dashboard/chatbots/$id/settings'
    | '/dashboard/chatbots/$id/sources'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/_layout'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/renew-password/'
    | '/auth/reset-password/'
    | '/auth/verify-email/'
    | '/_authenticated/dashboard/_layout/chatbots'
    | '/_authenticated/dashboard/_layout/knowledge-base'
    | '/_authenticated/dashboard/_layout/usages'
    | '/_authenticated/dashboard/chatbots/$id'
    | '/_authenticated/dashboard/chatbots/create'
    | '/_authenticated/dashboard/chatbots/demo'
    | '/_authenticated/dashboard/knowledge-base/create'
    | '/_authenticated/dashboard/tenants/create'
    | '/_authenticated/dashboard/_layout/'
    | '/_authenticated/dashboard/_layout/settings/billing'
    | '/_authenticated/dashboard/_layout/settings/general'
    | '/_authenticated/dashboard/_layout/settings/members'
    | '/_authenticated/dashboard/_layout/settings/plans'
    | '/_authenticated/dashboard/_layout/settings/security'
    | '/_authenticated/dashboard/chatbots/$id/playground'
    | '/_authenticated/dashboard/chatbots/$id/settings'
    | '/_authenticated/dashboard/chatbots/$id/widget'
    | '/_authenticated/dashboard/chatbots/create/files'
    | '/_authenticated/dashboard/chatbots/create/knowledge'
    | '/_authenticated/dashboard/chatbots/create/text'
    | '/_authenticated/dashboard/chatbots/create/websites'
    | '/_authenticated/dashboard/knowledge-base/create/files'
    | '/_authenticated/dashboard/knowledge-base/create/knowledge'
    | '/_authenticated/dashboard/knowledge-base/create/text'
    | '/_authenticated/dashboard/knowledge-base/create/websites'
    | '/_authenticated/dashboard/chatbots/$id/'
    | '/_authenticated/dashboard/chatbots/create/'
    | '/_authenticated/dashboard/knowledge-base/create/'
    | '/_authenticated/dashboard/chatbots/$id/settings/ai'
    | '/_authenticated/dashboard/chatbots/$id/settings/chat-interface'
    | '/_authenticated/dashboard/chatbots/$id/settings/general'
    | '/_authenticated/dashboard/chatbots/$id/settings/security'
    | '/_authenticated/dashboard/chatbots/$id/sources/files'
    | '/_authenticated/dashboard/chatbots/$id/sources/knowledge-bases'
    | '/_authenticated/dashboard/chatbots/$id/sources/text'
    | '/_authenticated/dashboard/chatbots/$id/sources/websites'
    | '/_authenticated/dashboard/chatbots/$id/settings/'
    | '/_authenticated/dashboard/chatbots/$id/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthRenewPasswordIndexRoute: typeof AuthRenewPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/renew-password/': {
      id: '/auth/renew-password/'
      path: '/auth/renew-password'
      fullPath: '/auth/renew-password'
      preLoaderRoute: typeof AuthRenewPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/_layout': {
      id: '/_authenticated/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/_layout/': {
      id: '/_authenticated/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/tenants/create': {
      id: '/_authenticated/dashboard/tenants/create'
      path: '/tenants/create'
      fullPath: '/dashboard/tenants/create'
      preLoaderRoute: typeof AuthenticatedDashboardTenantsCreateRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/knowledge-base/create': {
      id: '/_authenticated/dashboard/knowledge-base/create'
      path: '/knowledge-base/create'
      fullPath: '/dashboard/knowledge-base/create'
      preLoaderRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/chatbots/demo': {
      id: '/_authenticated/dashboard/chatbots/demo'
      path: '/chatbots/demo'
      fullPath: '/dashboard/chatbots/demo'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsDemoRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/chatbots/create': {
      id: '/_authenticated/dashboard/chatbots/create'
      path: '/chatbots/create'
      fullPath: '/dashboard/chatbots/create'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsCreateRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/chatbots/$id': {
      id: '/_authenticated/dashboard/chatbots/$id'
      path: '/chatbots/$id'
      fullPath: '/dashboard/chatbots/$id'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/_layout/usages': {
      id: '/_authenticated/dashboard/_layout/usages'
      path: '/usages'
      fullPath: '/dashboard/usages'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutUsagesRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/_layout/knowledge-base': {
      id: '/_authenticated/dashboard/_layout/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/dashboard/knowledge-base'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/_layout/chatbots': {
      id: '/_authenticated/dashboard/_layout/chatbots'
      path: '/chatbots'
      fullPath: '/dashboard/chatbots'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutChatbotsRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/knowledge-base/create/': {
      id: '/_authenticated/dashboard/knowledge-base/create/'
      path: '/'
      fullPath: '/dashboard/knowledge-base/create/'
      preLoaderRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateRoute
    }
    '/_authenticated/dashboard/chatbots/create/': {
      id: '/_authenticated/dashboard/chatbots/create/'
      path: '/'
      fullPath: '/dashboard/chatbots/create/'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsCreateIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsCreateRoute
    }
    '/_authenticated/dashboard/chatbots/$id/': {
      id: '/_authenticated/dashboard/chatbots/$id/'
      path: '/'
      fullPath: '/dashboard/chatbots/$id/'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdRoute
    }
    '/_authenticated/dashboard/knowledge-base/create/websites': {
      id: '/_authenticated/dashboard/knowledge-base/create/websites'
      path: '/websites'
      fullPath: '/dashboard/knowledge-base/create/websites'
      preLoaderRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateWebsitesRouteImport
      parentRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateRoute
    }
    '/_authenticated/dashboard/knowledge-base/create/text': {
      id: '/_authenticated/dashboard/knowledge-base/create/text'
      path: '/text'
      fullPath: '/dashboard/knowledge-base/create/text'
      preLoaderRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateTextRouteImport
      parentRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateRoute
    }
    '/_authenticated/dashboard/knowledge-base/create/knowledge': {
      id: '/_authenticated/dashboard/knowledge-base/create/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge-base/create/knowledge'
      preLoaderRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRouteImport
      parentRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateRoute
    }
    '/_authenticated/dashboard/knowledge-base/create/files': {
      id: '/_authenticated/dashboard/knowledge-base/create/files'
      path: '/files'
      fullPath: '/dashboard/knowledge-base/create/files'
      preLoaderRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateFilesRouteImport
      parentRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateRoute
    }
    '/_authenticated/dashboard/chatbots/create/websites': {
      id: '/_authenticated/dashboard/chatbots/create/websites'
      path: '/websites'
      fullPath: '/dashboard/chatbots/create/websites'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsCreateWebsitesRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsCreateRoute
    }
    '/_authenticated/dashboard/chatbots/create/text': {
      id: '/_authenticated/dashboard/chatbots/create/text'
      path: '/text'
      fullPath: '/dashboard/chatbots/create/text'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsCreateTextRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsCreateRoute
    }
    '/_authenticated/dashboard/chatbots/create/knowledge': {
      id: '/_authenticated/dashboard/chatbots/create/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/chatbots/create/knowledge'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsCreateKnowledgeRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsCreateRoute
    }
    '/_authenticated/dashboard/chatbots/create/files': {
      id: '/_authenticated/dashboard/chatbots/create/files'
      path: '/files'
      fullPath: '/dashboard/chatbots/create/files'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsCreateFilesRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsCreateRoute
    }
    '/_authenticated/dashboard/chatbots/$id/widget': {
      id: '/_authenticated/dashboard/chatbots/$id/widget'
      path: '/widget'
      fullPath: '/dashboard/chatbots/$id/widget'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdWidgetRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdRoute
    }
    '/_authenticated/dashboard/chatbots/$id/settings': {
      id: '/_authenticated/dashboard/chatbots/$id/settings'
      path: '/settings'
      fullPath: '/dashboard/chatbots/$id/settings'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSettingsRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdRoute
    }
    '/_authenticated/dashboard/chatbots/$id/playground': {
      id: '/_authenticated/dashboard/chatbots/$id/playground'
      path: '/playground'
      fullPath: '/dashboard/chatbots/$id/playground'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdPlaygroundRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdRoute
    }
    '/_authenticated/dashboard/_layout/settings/security': {
      id: '/_authenticated/dashboard/_layout/settings/security'
      path: '/settings/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/_layout/settings/plans': {
      id: '/_authenticated/dashboard/_layout/settings/plans'
      path: '/settings/plans'
      fullPath: '/dashboard/settings/plans'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutSettingsPlansRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/_layout/settings/members': {
      id: '/_authenticated/dashboard/_layout/settings/members'
      path: '/settings/members'
      fullPath: '/dashboard/settings/members'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutSettingsMembersRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/_layout/settings/general': {
      id: '/_authenticated/dashboard/_layout/settings/general'
      path: '/settings/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/_layout/settings/billing': {
      id: '/_authenticated/dashboard/_layout/settings/billing'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof AuthenticatedDashboardLayoutSettingsBillingRouteImport
      parentRoute: typeof AuthenticatedDashboardLayoutRoute
    }
    '/_authenticated/dashboard/chatbots/$id/sources/': {
      id: '/_authenticated/dashboard/chatbots/$id/sources/'
      path: '/sources'
      fullPath: '/dashboard/chatbots/$id/sources'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSourcesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdRoute
    }
    '/_authenticated/dashboard/chatbots/$id/settings/': {
      id: '/_authenticated/dashboard/chatbots/$id/settings/'
      path: '/'
      fullPath: '/dashboard/chatbots/$id/settings/'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdSettingsRoute
    }
    '/_authenticated/dashboard/chatbots/$id/sources/websites': {
      id: '/_authenticated/dashboard/chatbots/$id/sources/websites'
      path: '/sources/websites'
      fullPath: '/dashboard/chatbots/$id/sources/websites'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSourcesWebsitesRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdRoute
    }
    '/_authenticated/dashboard/chatbots/$id/sources/text': {
      id: '/_authenticated/dashboard/chatbots/$id/sources/text'
      path: '/sources/text'
      fullPath: '/dashboard/chatbots/$id/sources/text'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSourcesTextRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdRoute
    }
    '/_authenticated/dashboard/chatbots/$id/sources/knowledge-bases': {
      id: '/_authenticated/dashboard/chatbots/$id/sources/knowledge-bases'
      path: '/sources/knowledge-bases'
      fullPath: '/dashboard/chatbots/$id/sources/knowledge-bases'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdRoute
    }
    '/_authenticated/dashboard/chatbots/$id/sources/files': {
      id: '/_authenticated/dashboard/chatbots/$id/sources/files'
      path: '/sources/files'
      fullPath: '/dashboard/chatbots/$id/sources/files'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSourcesFilesRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdRoute
    }
    '/_authenticated/dashboard/chatbots/$id/settings/security': {
      id: '/_authenticated/dashboard/chatbots/$id/settings/security'
      path: '/security'
      fullPath: '/dashboard/chatbots/$id/settings/security'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdSettingsRoute
    }
    '/_authenticated/dashboard/chatbots/$id/settings/general': {
      id: '/_authenticated/dashboard/chatbots/$id/settings/general'
      path: '/general'
      fullPath: '/dashboard/chatbots/$id/settings/general'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdSettingsRoute
    }
    '/_authenticated/dashboard/chatbots/$id/settings/chat-interface': {
      id: '/_authenticated/dashboard/chatbots/$id/settings/chat-interface'
      path: '/chat-interface'
      fullPath: '/dashboard/chatbots/$id/settings/chat-interface'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdSettingsRoute
    }
    '/_authenticated/dashboard/chatbots/$id/settings/ai': {
      id: '/_authenticated/dashboard/chatbots/$id/settings/ai'
      path: '/ai'
      fullPath: '/dashboard/chatbots/$id/settings/ai'
      preLoaderRoute: typeof AuthenticatedDashboardChatbotsIdSettingsAiRouteImport
      parentRoute: typeof AuthenticatedDashboardChatbotsIdSettingsRoute
    }
  }
}

interface AuthenticatedDashboardLayoutRouteChildren {
  AuthenticatedDashboardLayoutChatbotsRoute: typeof AuthenticatedDashboardLayoutChatbotsRoute
  AuthenticatedDashboardLayoutKnowledgeBaseRoute: typeof AuthenticatedDashboardLayoutKnowledgeBaseRoute
  AuthenticatedDashboardLayoutUsagesRoute: typeof AuthenticatedDashboardLayoutUsagesRoute
  AuthenticatedDashboardLayoutIndexRoute: typeof AuthenticatedDashboardLayoutIndexRoute
  AuthenticatedDashboardLayoutSettingsBillingRoute: typeof AuthenticatedDashboardLayoutSettingsBillingRoute
  AuthenticatedDashboardLayoutSettingsGeneralRoute: typeof AuthenticatedDashboardLayoutSettingsGeneralRoute
  AuthenticatedDashboardLayoutSettingsMembersRoute: typeof AuthenticatedDashboardLayoutSettingsMembersRoute
  AuthenticatedDashboardLayoutSettingsPlansRoute: typeof AuthenticatedDashboardLayoutSettingsPlansRoute
  AuthenticatedDashboardLayoutSettingsSecurityRoute: typeof AuthenticatedDashboardLayoutSettingsSecurityRoute
}

const AuthenticatedDashboardLayoutRouteChildren: AuthenticatedDashboardLayoutRouteChildren =
  {
    AuthenticatedDashboardLayoutChatbotsRoute:
      AuthenticatedDashboardLayoutChatbotsRoute,
    AuthenticatedDashboardLayoutKnowledgeBaseRoute:
      AuthenticatedDashboardLayoutKnowledgeBaseRoute,
    AuthenticatedDashboardLayoutUsagesRoute:
      AuthenticatedDashboardLayoutUsagesRoute,
    AuthenticatedDashboardLayoutIndexRoute:
      AuthenticatedDashboardLayoutIndexRoute,
    AuthenticatedDashboardLayoutSettingsBillingRoute:
      AuthenticatedDashboardLayoutSettingsBillingRoute,
    AuthenticatedDashboardLayoutSettingsGeneralRoute:
      AuthenticatedDashboardLayoutSettingsGeneralRoute,
    AuthenticatedDashboardLayoutSettingsMembersRoute:
      AuthenticatedDashboardLayoutSettingsMembersRoute,
    AuthenticatedDashboardLayoutSettingsPlansRoute:
      AuthenticatedDashboardLayoutSettingsPlansRoute,
    AuthenticatedDashboardLayoutSettingsSecurityRoute:
      AuthenticatedDashboardLayoutSettingsSecurityRoute,
  }

const AuthenticatedDashboardLayoutRouteWithChildren =
  AuthenticatedDashboardLayoutRoute._addFileChildren(
    AuthenticatedDashboardLayoutRouteChildren,
  )

interface AuthenticatedDashboardChatbotsIdSettingsRouteChildren {
  AuthenticatedDashboardChatbotsIdSettingsAiRoute: typeof AuthenticatedDashboardChatbotsIdSettingsAiRoute
  AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRoute: typeof AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRoute
  AuthenticatedDashboardChatbotsIdSettingsGeneralRoute: typeof AuthenticatedDashboardChatbotsIdSettingsGeneralRoute
  AuthenticatedDashboardChatbotsIdSettingsSecurityRoute: typeof AuthenticatedDashboardChatbotsIdSettingsSecurityRoute
  AuthenticatedDashboardChatbotsIdSettingsIndexRoute: typeof AuthenticatedDashboardChatbotsIdSettingsIndexRoute
}

const AuthenticatedDashboardChatbotsIdSettingsRouteChildren: AuthenticatedDashboardChatbotsIdSettingsRouteChildren =
  {
    AuthenticatedDashboardChatbotsIdSettingsAiRoute:
      AuthenticatedDashboardChatbotsIdSettingsAiRoute,
    AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRoute:
      AuthenticatedDashboardChatbotsIdSettingsChatInterfaceRoute,
    AuthenticatedDashboardChatbotsIdSettingsGeneralRoute:
      AuthenticatedDashboardChatbotsIdSettingsGeneralRoute,
    AuthenticatedDashboardChatbotsIdSettingsSecurityRoute:
      AuthenticatedDashboardChatbotsIdSettingsSecurityRoute,
    AuthenticatedDashboardChatbotsIdSettingsIndexRoute:
      AuthenticatedDashboardChatbotsIdSettingsIndexRoute,
  }

const AuthenticatedDashboardChatbotsIdSettingsRouteWithChildren =
  AuthenticatedDashboardChatbotsIdSettingsRoute._addFileChildren(
    AuthenticatedDashboardChatbotsIdSettingsRouteChildren,
  )

interface AuthenticatedDashboardChatbotsIdRouteChildren {
  AuthenticatedDashboardChatbotsIdPlaygroundRoute: typeof AuthenticatedDashboardChatbotsIdPlaygroundRoute
  AuthenticatedDashboardChatbotsIdSettingsRoute: typeof AuthenticatedDashboardChatbotsIdSettingsRouteWithChildren
  AuthenticatedDashboardChatbotsIdWidgetRoute: typeof AuthenticatedDashboardChatbotsIdWidgetRoute
  AuthenticatedDashboardChatbotsIdIndexRoute: typeof AuthenticatedDashboardChatbotsIdIndexRoute
  AuthenticatedDashboardChatbotsIdSourcesFilesRoute: typeof AuthenticatedDashboardChatbotsIdSourcesFilesRoute
  AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRoute: typeof AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRoute
  AuthenticatedDashboardChatbotsIdSourcesTextRoute: typeof AuthenticatedDashboardChatbotsIdSourcesTextRoute
  AuthenticatedDashboardChatbotsIdSourcesWebsitesRoute: typeof AuthenticatedDashboardChatbotsIdSourcesWebsitesRoute
  AuthenticatedDashboardChatbotsIdSourcesIndexRoute: typeof AuthenticatedDashboardChatbotsIdSourcesIndexRoute
}

const AuthenticatedDashboardChatbotsIdRouteChildren: AuthenticatedDashboardChatbotsIdRouteChildren =
  {
    AuthenticatedDashboardChatbotsIdPlaygroundRoute:
      AuthenticatedDashboardChatbotsIdPlaygroundRoute,
    AuthenticatedDashboardChatbotsIdSettingsRoute:
      AuthenticatedDashboardChatbotsIdSettingsRouteWithChildren,
    AuthenticatedDashboardChatbotsIdWidgetRoute:
      AuthenticatedDashboardChatbotsIdWidgetRoute,
    AuthenticatedDashboardChatbotsIdIndexRoute:
      AuthenticatedDashboardChatbotsIdIndexRoute,
    AuthenticatedDashboardChatbotsIdSourcesFilesRoute:
      AuthenticatedDashboardChatbotsIdSourcesFilesRoute,
    AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRoute:
      AuthenticatedDashboardChatbotsIdSourcesKnowledgeBasesRoute,
    AuthenticatedDashboardChatbotsIdSourcesTextRoute:
      AuthenticatedDashboardChatbotsIdSourcesTextRoute,
    AuthenticatedDashboardChatbotsIdSourcesWebsitesRoute:
      AuthenticatedDashboardChatbotsIdSourcesWebsitesRoute,
    AuthenticatedDashboardChatbotsIdSourcesIndexRoute:
      AuthenticatedDashboardChatbotsIdSourcesIndexRoute,
  }

const AuthenticatedDashboardChatbotsIdRouteWithChildren =
  AuthenticatedDashboardChatbotsIdRoute._addFileChildren(
    AuthenticatedDashboardChatbotsIdRouteChildren,
  )

interface AuthenticatedDashboardChatbotsCreateRouteChildren {
  AuthenticatedDashboardChatbotsCreateFilesRoute: typeof AuthenticatedDashboardChatbotsCreateFilesRoute
  AuthenticatedDashboardChatbotsCreateKnowledgeRoute: typeof AuthenticatedDashboardChatbotsCreateKnowledgeRoute
  AuthenticatedDashboardChatbotsCreateTextRoute: typeof AuthenticatedDashboardChatbotsCreateTextRoute
  AuthenticatedDashboardChatbotsCreateWebsitesRoute: typeof AuthenticatedDashboardChatbotsCreateWebsitesRoute
  AuthenticatedDashboardChatbotsCreateIndexRoute: typeof AuthenticatedDashboardChatbotsCreateIndexRoute
}

const AuthenticatedDashboardChatbotsCreateRouteChildren: AuthenticatedDashboardChatbotsCreateRouteChildren =
  {
    AuthenticatedDashboardChatbotsCreateFilesRoute:
      AuthenticatedDashboardChatbotsCreateFilesRoute,
    AuthenticatedDashboardChatbotsCreateKnowledgeRoute:
      AuthenticatedDashboardChatbotsCreateKnowledgeRoute,
    AuthenticatedDashboardChatbotsCreateTextRoute:
      AuthenticatedDashboardChatbotsCreateTextRoute,
    AuthenticatedDashboardChatbotsCreateWebsitesRoute:
      AuthenticatedDashboardChatbotsCreateWebsitesRoute,
    AuthenticatedDashboardChatbotsCreateIndexRoute:
      AuthenticatedDashboardChatbotsCreateIndexRoute,
  }

const AuthenticatedDashboardChatbotsCreateRouteWithChildren =
  AuthenticatedDashboardChatbotsCreateRoute._addFileChildren(
    AuthenticatedDashboardChatbotsCreateRouteChildren,
  )

interface AuthenticatedDashboardKnowledgeBaseCreateRouteChildren {
  AuthenticatedDashboardKnowledgeBaseCreateFilesRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateFilesRoute
  AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRoute
  AuthenticatedDashboardKnowledgeBaseCreateTextRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateTextRoute
  AuthenticatedDashboardKnowledgeBaseCreateWebsitesRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateWebsitesRoute
  AuthenticatedDashboardKnowledgeBaseCreateIndexRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateIndexRoute
}

const AuthenticatedDashboardKnowledgeBaseCreateRouteChildren: AuthenticatedDashboardKnowledgeBaseCreateRouteChildren =
  {
    AuthenticatedDashboardKnowledgeBaseCreateFilesRoute:
      AuthenticatedDashboardKnowledgeBaseCreateFilesRoute,
    AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRoute:
      AuthenticatedDashboardKnowledgeBaseCreateKnowledgeRoute,
    AuthenticatedDashboardKnowledgeBaseCreateTextRoute:
      AuthenticatedDashboardKnowledgeBaseCreateTextRoute,
    AuthenticatedDashboardKnowledgeBaseCreateWebsitesRoute:
      AuthenticatedDashboardKnowledgeBaseCreateWebsitesRoute,
    AuthenticatedDashboardKnowledgeBaseCreateIndexRoute:
      AuthenticatedDashboardKnowledgeBaseCreateIndexRoute,
  }

const AuthenticatedDashboardKnowledgeBaseCreateRouteWithChildren =
  AuthenticatedDashboardKnowledgeBaseCreateRoute._addFileChildren(
    AuthenticatedDashboardKnowledgeBaseCreateRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardLayoutRoute: typeof AuthenticatedDashboardLayoutRouteWithChildren
  AuthenticatedDashboardChatbotsIdRoute: typeof AuthenticatedDashboardChatbotsIdRouteWithChildren
  AuthenticatedDashboardChatbotsCreateRoute: typeof AuthenticatedDashboardChatbotsCreateRouteWithChildren
  AuthenticatedDashboardChatbotsDemoRoute: typeof AuthenticatedDashboardChatbotsDemoRoute
  AuthenticatedDashboardKnowledgeBaseCreateRoute: typeof AuthenticatedDashboardKnowledgeBaseCreateRouteWithChildren
  AuthenticatedDashboardTenantsCreateRoute: typeof AuthenticatedDashboardTenantsCreateRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardLayoutRoute:
      AuthenticatedDashboardLayoutRouteWithChildren,
    AuthenticatedDashboardChatbotsIdRoute:
      AuthenticatedDashboardChatbotsIdRouteWithChildren,
    AuthenticatedDashboardChatbotsCreateRoute:
      AuthenticatedDashboardChatbotsCreateRouteWithChildren,
    AuthenticatedDashboardChatbotsDemoRoute:
      AuthenticatedDashboardChatbotsDemoRoute,
    AuthenticatedDashboardKnowledgeBaseCreateRoute:
      AuthenticatedDashboardKnowledgeBaseCreateRouteWithChildren,
    AuthenticatedDashboardTenantsCreateRoute:
      AuthenticatedDashboardTenantsCreateRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthRenewPasswordIndexRoute: AuthRenewPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
