/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardLayoutRouteImport } from './routes/dashboard/_layout'
import { Route as DashboardLayoutIndexRouteImport } from './routes/dashboard/_layout/index'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/auth/verify-email/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthRenewPasswordIndexRouteImport } from './routes/auth/renew-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DashboardTenantsCreateRouteImport } from './routes/dashboard/tenants/create'
import { Route as DashboardKnowledgeBaseCreateRouteImport } from './routes/dashboard/knowledge-base/create'
import { Route as DashboardChatbotsDemoRouteImport } from './routes/dashboard/chatbots/demo'
import { Route as DashboardChatbotsCreateRouteImport } from './routes/dashboard/chatbots/create'
import { Route as DashboardChatbotsIdRouteImport } from './routes/dashboard/chatbots/$id'
import { Route as DashboardLayoutUsagesRouteImport } from './routes/dashboard/_layout/usages'
import { Route as DashboardLayoutKnowledgeBaseRouteImport } from './routes/dashboard/_layout/knowledge-base'
import { Route as DashboardLayoutChatbotsRouteImport } from './routes/dashboard/_layout/chatbots'
import { Route as DashboardKnowledgeBaseCreateIndexRouteImport } from './routes/dashboard/knowledge-base/create/index'
import { Route as DashboardChatbotsCreateIndexRouteImport } from './routes/dashboard/chatbots/create/index'
import { Route as DashboardChatbotsIdIndexRouteImport } from './routes/dashboard/chatbots/$id/index'
import { Route as DashboardKnowledgeBaseCreateWebsitesRouteImport } from './routes/dashboard/knowledge-base/create/websites'
import { Route as DashboardKnowledgeBaseCreateTextRouteImport } from './routes/dashboard/knowledge-base/create/text'
import { Route as DashboardKnowledgeBaseCreateKnowledgeRouteImport } from './routes/dashboard/knowledge-base/create/knowledge'
import { Route as DashboardKnowledgeBaseCreateFilesRouteImport } from './routes/dashboard/knowledge-base/create/files'
import { Route as DashboardChatbotsCreateWebsitesRouteImport } from './routes/dashboard/chatbots/create/websites'
import { Route as DashboardChatbotsCreateTextRouteImport } from './routes/dashboard/chatbots/create/text'
import { Route as DashboardChatbotsCreateKnowledgeRouteImport } from './routes/dashboard/chatbots/create/knowledge'
import { Route as DashboardChatbotsCreateFilesRouteImport } from './routes/dashboard/chatbots/create/files'
import { Route as DashboardChatbotsIdWidgetRouteImport } from './routes/dashboard/chatbots/$id/widget'
import { Route as DashboardChatbotsIdSettingsRouteImport } from './routes/dashboard/chatbots/$id/settings'
import { Route as DashboardChatbotsIdPlaygroundRouteImport } from './routes/dashboard/chatbots/$id/playground'
import { Route as DashboardLayoutSettingsSecurityRouteImport } from './routes/dashboard/_layout/settings/security'
import { Route as DashboardLayoutSettingsPlansRouteImport } from './routes/dashboard/_layout/settings/plans'
import { Route as DashboardLayoutSettingsMembersRouteImport } from './routes/dashboard/_layout/settings/members'
import { Route as DashboardLayoutSettingsGeneralRouteImport } from './routes/dashboard/_layout/settings/general'
import { Route as DashboardLayoutSettingsBillingRouteImport } from './routes/dashboard/_layout/settings/billing'
import { Route as DashboardChatbotsIdSourcesIndexRouteImport } from './routes/dashboard/chatbots/$id/sources/index'
import { Route as DashboardChatbotsIdSettingsIndexRouteImport } from './routes/dashboard/chatbots/$id/settings/index'
import { Route as DashboardChatbotsIdSourcesWebsitesRouteImport } from './routes/dashboard/chatbots/$id/sources/websites'
import { Route as DashboardChatbotsIdSourcesTextRouteImport } from './routes/dashboard/chatbots/$id/sources/text'
import { Route as DashboardChatbotsIdSourcesKnowledgeBasesRouteImport } from './routes/dashboard/chatbots/$id/sources/knowledge-bases'
import { Route as DashboardChatbotsIdSourcesFilesRouteImport } from './routes/dashboard/chatbots/$id/sources/files'
import { Route as DashboardChatbotsIdSettingsSecurityRouteImport } from './routes/dashboard/chatbots/$id/settings/security'
import { Route as DashboardChatbotsIdSettingsGeneralRouteImport } from './routes/dashboard/chatbots/$id/settings/general'
import { Route as DashboardChatbotsIdSettingsChatInterfaceRouteImport } from './routes/dashboard/chatbots/$id/settings/chat-interface'
import { Route as DashboardChatbotsIdSettingsAiRouteImport } from './routes/dashboard/chatbots/$id/settings/ai'

const DashboardRouteImport = createFileRoute('/dashboard')()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLayoutIndexRoute = DashboardLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/auth/verify-email/',
  path: '/auth/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRenewPasswordIndexRoute = AuthRenewPasswordIndexRouteImport.update({
  id: '/auth/renew-password/',
  path: '/auth/renew-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantsCreateRoute = DashboardTenantsCreateRouteImport.update({
  id: '/tenants/create',
  path: '/tenants/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKnowledgeBaseCreateRoute =
  DashboardKnowledgeBaseCreateRouteImport.update({
    id: '/knowledge-base/create',
    path: '/knowledge-base/create',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardChatbotsDemoRoute = DashboardChatbotsDemoRouteImport.update({
  id: '/chatbots/demo',
  path: '/chatbots/demo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatbotsCreateRoute = DashboardChatbotsCreateRouteImport.update({
  id: '/chatbots/create',
  path: '/chatbots/create',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatbotsIdRoute = DashboardChatbotsIdRouteImport.update({
  id: '/chatbots/$id',
  path: '/chatbots/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLayoutUsagesRoute = DashboardLayoutUsagesRouteImport.update({
  id: '/usages',
  path: '/usages',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardLayoutKnowledgeBaseRoute =
  DashboardLayoutKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutChatbotsRoute = DashboardLayoutChatbotsRouteImport.update({
  id: '/chatbots',
  path: '/chatbots',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardKnowledgeBaseCreateIndexRoute =
  DashboardKnowledgeBaseCreateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardKnowledgeBaseCreateRoute,
  } as any)
const DashboardChatbotsCreateIndexRoute =
  DashboardChatbotsCreateIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardChatbotsCreateRoute,
  } as any)
const DashboardChatbotsIdIndexRoute =
  DashboardChatbotsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardChatbotsIdRoute,
  } as any)
const DashboardKnowledgeBaseCreateWebsitesRoute =
  DashboardKnowledgeBaseCreateWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => DashboardKnowledgeBaseCreateRoute,
  } as any)
const DashboardKnowledgeBaseCreateTextRoute =
  DashboardKnowledgeBaseCreateTextRouteImport.update({
    id: '/text',
    path: '/text',
    getParentRoute: () => DashboardKnowledgeBaseCreateRoute,
  } as any)
const DashboardKnowledgeBaseCreateKnowledgeRoute =
  DashboardKnowledgeBaseCreateKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => DashboardKnowledgeBaseCreateRoute,
  } as any)
const DashboardKnowledgeBaseCreateFilesRoute =
  DashboardKnowledgeBaseCreateFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => DashboardKnowledgeBaseCreateRoute,
  } as any)
const DashboardChatbotsCreateWebsitesRoute =
  DashboardChatbotsCreateWebsitesRouteImport.update({
    id: '/websites',
    path: '/websites',
    getParentRoute: () => DashboardChatbotsCreateRoute,
  } as any)
const DashboardChatbotsCreateTextRoute =
  DashboardChatbotsCreateTextRouteImport.update({
    id: '/text',
    path: '/text',
    getParentRoute: () => DashboardChatbotsCreateRoute,
  } as any)
const DashboardChatbotsCreateKnowledgeRoute =
  DashboardChatbotsCreateKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => DashboardChatbotsCreateRoute,
  } as any)
const DashboardChatbotsCreateFilesRoute =
  DashboardChatbotsCreateFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => DashboardChatbotsCreateRoute,
  } as any)
const DashboardChatbotsIdWidgetRoute =
  DashboardChatbotsIdWidgetRouteImport.update({
    id: '/widget',
    path: '/widget',
    getParentRoute: () => DashboardChatbotsIdRoute,
  } as any)
const DashboardChatbotsIdSettingsRoute =
  DashboardChatbotsIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardChatbotsIdRoute,
  } as any)
const DashboardChatbotsIdPlaygroundRoute =
  DashboardChatbotsIdPlaygroundRouteImport.update({
    id: '/playground',
    path: '/playground',
    getParentRoute: () => DashboardChatbotsIdRoute,
  } as any)
const DashboardLayoutSettingsSecurityRoute =
  DashboardLayoutSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutSettingsPlansRoute =
  DashboardLayoutSettingsPlansRouteImport.update({
    id: '/settings/plans',
    path: '/settings/plans',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutSettingsMembersRoute =
  DashboardLayoutSettingsMembersRouteImport.update({
    id: '/settings/members',
    path: '/settings/members',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutSettingsGeneralRoute =
  DashboardLayoutSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardLayoutSettingsBillingRoute =
  DashboardLayoutSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardLayoutRoute,
  } as any)
const DashboardChatbotsIdSourcesIndexRoute =
  DashboardChatbotsIdSourcesIndexRouteImport.update({
    id: '/sources/',
    path: '/sources/',
    getParentRoute: () => DashboardChatbotsIdRoute,
  } as any)
const DashboardChatbotsIdSettingsIndexRoute =
  DashboardChatbotsIdSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardChatbotsIdSettingsRoute,
  } as any)
const DashboardChatbotsIdSourcesWebsitesRoute =
  DashboardChatbotsIdSourcesWebsitesRouteImport.update({
    id: '/sources/websites',
    path: '/sources/websites',
    getParentRoute: () => DashboardChatbotsIdRoute,
  } as any)
const DashboardChatbotsIdSourcesTextRoute =
  DashboardChatbotsIdSourcesTextRouteImport.update({
    id: '/sources/text',
    path: '/sources/text',
    getParentRoute: () => DashboardChatbotsIdRoute,
  } as any)
const DashboardChatbotsIdSourcesKnowledgeBasesRoute =
  DashboardChatbotsIdSourcesKnowledgeBasesRouteImport.update({
    id: '/sources/knowledge-bases',
    path: '/sources/knowledge-bases',
    getParentRoute: () => DashboardChatbotsIdRoute,
  } as any)
const DashboardChatbotsIdSourcesFilesRoute =
  DashboardChatbotsIdSourcesFilesRouteImport.update({
    id: '/sources/files',
    path: '/sources/files',
    getParentRoute: () => DashboardChatbotsIdRoute,
  } as any)
const DashboardChatbotsIdSettingsSecurityRoute =
  DashboardChatbotsIdSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardChatbotsIdSettingsRoute,
  } as any)
const DashboardChatbotsIdSettingsGeneralRoute =
  DashboardChatbotsIdSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => DashboardChatbotsIdSettingsRoute,
  } as any)
const DashboardChatbotsIdSettingsChatInterfaceRoute =
  DashboardChatbotsIdSettingsChatInterfaceRouteImport.update({
    id: '/chat-interface',
    path: '/chat-interface',
    getParentRoute: () => DashboardChatbotsIdSettingsRoute,
  } as any)
const DashboardChatbotsIdSettingsAiRoute =
  DashboardChatbotsIdSettingsAiRouteImport.update({
    id: '/ai',
    path: '/ai',
    getParentRoute: () => DashboardChatbotsIdSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/chatbots': typeof DashboardLayoutChatbotsRoute
  '/dashboard/knowledge-base': typeof DashboardLayoutKnowledgeBaseRoute
  '/dashboard/usages': typeof DashboardLayoutUsagesRoute
  '/dashboard/chatbots/$id': typeof DashboardChatbotsIdRouteWithChildren
  '/dashboard/chatbots/create': typeof DashboardChatbotsCreateRouteWithChildren
  '/dashboard/chatbots/demo': typeof DashboardChatbotsDemoRoute
  '/dashboard/knowledge-base/create': typeof DashboardKnowledgeBaseCreateRouteWithChildren
  '/dashboard/tenants/create': typeof DashboardTenantsCreateRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/renew-password': typeof AuthRenewPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/dashboard/': typeof DashboardLayoutIndexRoute
  '/dashboard/settings/billing': typeof DashboardLayoutSettingsBillingRoute
  '/dashboard/settings/general': typeof DashboardLayoutSettingsGeneralRoute
  '/dashboard/settings/members': typeof DashboardLayoutSettingsMembersRoute
  '/dashboard/settings/plans': typeof DashboardLayoutSettingsPlansRoute
  '/dashboard/settings/security': typeof DashboardLayoutSettingsSecurityRoute
  '/dashboard/chatbots/$id/playground': typeof DashboardChatbotsIdPlaygroundRoute
  '/dashboard/chatbots/$id/settings': typeof DashboardChatbotsIdSettingsRouteWithChildren
  '/dashboard/chatbots/$id/widget': typeof DashboardChatbotsIdWidgetRoute
  '/dashboard/chatbots/create/files': typeof DashboardChatbotsCreateFilesRoute
  '/dashboard/chatbots/create/knowledge': typeof DashboardChatbotsCreateKnowledgeRoute
  '/dashboard/chatbots/create/text': typeof DashboardChatbotsCreateTextRoute
  '/dashboard/chatbots/create/websites': typeof DashboardChatbotsCreateWebsitesRoute
  '/dashboard/knowledge-base/create/files': typeof DashboardKnowledgeBaseCreateFilesRoute
  '/dashboard/knowledge-base/create/knowledge': typeof DashboardKnowledgeBaseCreateKnowledgeRoute
  '/dashboard/knowledge-base/create/text': typeof DashboardKnowledgeBaseCreateTextRoute
  '/dashboard/knowledge-base/create/websites': typeof DashboardKnowledgeBaseCreateWebsitesRoute
  '/dashboard/chatbots/$id/': typeof DashboardChatbotsIdIndexRoute
  '/dashboard/chatbots/create/': typeof DashboardChatbotsCreateIndexRoute
  '/dashboard/knowledge-base/create/': typeof DashboardKnowledgeBaseCreateIndexRoute
  '/dashboard/chatbots/$id/settings/ai': typeof DashboardChatbotsIdSettingsAiRoute
  '/dashboard/chatbots/$id/settings/chat-interface': typeof DashboardChatbotsIdSettingsChatInterfaceRoute
  '/dashboard/chatbots/$id/settings/general': typeof DashboardChatbotsIdSettingsGeneralRoute
  '/dashboard/chatbots/$id/settings/security': typeof DashboardChatbotsIdSettingsSecurityRoute
  '/dashboard/chatbots/$id/sources/files': typeof DashboardChatbotsIdSourcesFilesRoute
  '/dashboard/chatbots/$id/sources/knowledge-bases': typeof DashboardChatbotsIdSourcesKnowledgeBasesRoute
  '/dashboard/chatbots/$id/sources/text': typeof DashboardChatbotsIdSourcesTextRoute
  '/dashboard/chatbots/$id/sources/websites': typeof DashboardChatbotsIdSourcesWebsitesRoute
  '/dashboard/chatbots/$id/settings/': typeof DashboardChatbotsIdSettingsIndexRoute
  '/dashboard/chatbots/$id/sources': typeof DashboardChatbotsIdSourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutIndexRoute
  '/dashboard/chatbots': typeof DashboardLayoutChatbotsRoute
  '/dashboard/knowledge-base': typeof DashboardLayoutKnowledgeBaseRoute
  '/dashboard/usages': typeof DashboardLayoutUsagesRoute
  '/dashboard/chatbots/demo': typeof DashboardChatbotsDemoRoute
  '/dashboard/tenants/create': typeof DashboardTenantsCreateRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/renew-password': typeof AuthRenewPasswordIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
  '/dashboard/settings/billing': typeof DashboardLayoutSettingsBillingRoute
  '/dashboard/settings/general': typeof DashboardLayoutSettingsGeneralRoute
  '/dashboard/settings/members': typeof DashboardLayoutSettingsMembersRoute
  '/dashboard/settings/plans': typeof DashboardLayoutSettingsPlansRoute
  '/dashboard/settings/security': typeof DashboardLayoutSettingsSecurityRoute
  '/dashboard/chatbots/$id/playground': typeof DashboardChatbotsIdPlaygroundRoute
  '/dashboard/chatbots/$id/widget': typeof DashboardChatbotsIdWidgetRoute
  '/dashboard/chatbots/create/files': typeof DashboardChatbotsCreateFilesRoute
  '/dashboard/chatbots/create/knowledge': typeof DashboardChatbotsCreateKnowledgeRoute
  '/dashboard/chatbots/create/text': typeof DashboardChatbotsCreateTextRoute
  '/dashboard/chatbots/create/websites': typeof DashboardChatbotsCreateWebsitesRoute
  '/dashboard/knowledge-base/create/files': typeof DashboardKnowledgeBaseCreateFilesRoute
  '/dashboard/knowledge-base/create/knowledge': typeof DashboardKnowledgeBaseCreateKnowledgeRoute
  '/dashboard/knowledge-base/create/text': typeof DashboardKnowledgeBaseCreateTextRoute
  '/dashboard/knowledge-base/create/websites': typeof DashboardKnowledgeBaseCreateWebsitesRoute
  '/dashboard/chatbots/$id': typeof DashboardChatbotsIdIndexRoute
  '/dashboard/chatbots/create': typeof DashboardChatbotsCreateIndexRoute
  '/dashboard/knowledge-base/create': typeof DashboardKnowledgeBaseCreateIndexRoute
  '/dashboard/chatbots/$id/settings/ai': typeof DashboardChatbotsIdSettingsAiRoute
  '/dashboard/chatbots/$id/settings/chat-interface': typeof DashboardChatbotsIdSettingsChatInterfaceRoute
  '/dashboard/chatbots/$id/settings/general': typeof DashboardChatbotsIdSettingsGeneralRoute
  '/dashboard/chatbots/$id/settings/security': typeof DashboardChatbotsIdSettingsSecurityRoute
  '/dashboard/chatbots/$id/sources/files': typeof DashboardChatbotsIdSourcesFilesRoute
  '/dashboard/chatbots/$id/sources/knowledge-bases': typeof DashboardChatbotsIdSourcesKnowledgeBasesRoute
  '/dashboard/chatbots/$id/sources/text': typeof DashboardChatbotsIdSourcesTextRoute
  '/dashboard/chatbots/$id/sources/websites': typeof DashboardChatbotsIdSourcesWebsitesRoute
  '/dashboard/chatbots/$id/settings': typeof DashboardChatbotsIdSettingsIndexRoute
  '/dashboard/chatbots/$id/sources': typeof DashboardChatbotsIdSourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_layout': typeof DashboardLayoutRouteWithChildren
  '/dashboard/_layout/chatbots': typeof DashboardLayoutChatbotsRoute
  '/dashboard/_layout/knowledge-base': typeof DashboardLayoutKnowledgeBaseRoute
  '/dashboard/_layout/usages': typeof DashboardLayoutUsagesRoute
  '/dashboard/chatbots/$id': typeof DashboardChatbotsIdRouteWithChildren
  '/dashboard/chatbots/create': typeof DashboardChatbotsCreateRouteWithChildren
  '/dashboard/chatbots/demo': typeof DashboardChatbotsDemoRoute
  '/dashboard/knowledge-base/create': typeof DashboardKnowledgeBaseCreateRouteWithChildren
  '/dashboard/tenants/create': typeof DashboardTenantsCreateRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/renew-password/': typeof AuthRenewPasswordIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
  '/dashboard/_layout/': typeof DashboardLayoutIndexRoute
  '/dashboard/_layout/settings/billing': typeof DashboardLayoutSettingsBillingRoute
  '/dashboard/_layout/settings/general': typeof DashboardLayoutSettingsGeneralRoute
  '/dashboard/_layout/settings/members': typeof DashboardLayoutSettingsMembersRoute
  '/dashboard/_layout/settings/plans': typeof DashboardLayoutSettingsPlansRoute
  '/dashboard/_layout/settings/security': typeof DashboardLayoutSettingsSecurityRoute
  '/dashboard/chatbots/$id/playground': typeof DashboardChatbotsIdPlaygroundRoute
  '/dashboard/chatbots/$id/settings': typeof DashboardChatbotsIdSettingsRouteWithChildren
  '/dashboard/chatbots/$id/widget': typeof DashboardChatbotsIdWidgetRoute
  '/dashboard/chatbots/create/files': typeof DashboardChatbotsCreateFilesRoute
  '/dashboard/chatbots/create/knowledge': typeof DashboardChatbotsCreateKnowledgeRoute
  '/dashboard/chatbots/create/text': typeof DashboardChatbotsCreateTextRoute
  '/dashboard/chatbots/create/websites': typeof DashboardChatbotsCreateWebsitesRoute
  '/dashboard/knowledge-base/create/files': typeof DashboardKnowledgeBaseCreateFilesRoute
  '/dashboard/knowledge-base/create/knowledge': typeof DashboardKnowledgeBaseCreateKnowledgeRoute
  '/dashboard/knowledge-base/create/text': typeof DashboardKnowledgeBaseCreateTextRoute
  '/dashboard/knowledge-base/create/websites': typeof DashboardKnowledgeBaseCreateWebsitesRoute
  '/dashboard/chatbots/$id/': typeof DashboardChatbotsIdIndexRoute
  '/dashboard/chatbots/create/': typeof DashboardChatbotsCreateIndexRoute
  '/dashboard/knowledge-base/create/': typeof DashboardKnowledgeBaseCreateIndexRoute
  '/dashboard/chatbots/$id/settings/ai': typeof DashboardChatbotsIdSettingsAiRoute
  '/dashboard/chatbots/$id/settings/chat-interface': typeof DashboardChatbotsIdSettingsChatInterfaceRoute
  '/dashboard/chatbots/$id/settings/general': typeof DashboardChatbotsIdSettingsGeneralRoute
  '/dashboard/chatbots/$id/settings/security': typeof DashboardChatbotsIdSettingsSecurityRoute
  '/dashboard/chatbots/$id/sources/files': typeof DashboardChatbotsIdSourcesFilesRoute
  '/dashboard/chatbots/$id/sources/knowledge-bases': typeof DashboardChatbotsIdSourcesKnowledgeBasesRoute
  '/dashboard/chatbots/$id/sources/text': typeof DashboardChatbotsIdSourcesTextRoute
  '/dashboard/chatbots/$id/sources/websites': typeof DashboardChatbotsIdSourcesWebsitesRoute
  '/dashboard/chatbots/$id/settings/': typeof DashboardChatbotsIdSettingsIndexRoute
  '/dashboard/chatbots/$id/sources/': typeof DashboardChatbotsIdSourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/chatbots'
    | '/dashboard/knowledge-base'
    | '/dashboard/usages'
    | '/dashboard/chatbots/$id'
    | '/dashboard/chatbots/create'
    | '/dashboard/chatbots/demo'
    | '/dashboard/knowledge-base/create'
    | '/dashboard/tenants/create'
    | '/auth/login'
    | '/auth/register'
    | '/auth/renew-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dashboard/'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/settings/members'
    | '/dashboard/settings/plans'
    | '/dashboard/settings/security'
    | '/dashboard/chatbots/$id/playground'
    | '/dashboard/chatbots/$id/settings'
    | '/dashboard/chatbots/$id/widget'
    | '/dashboard/chatbots/create/files'
    | '/dashboard/chatbots/create/knowledge'
    | '/dashboard/chatbots/create/text'
    | '/dashboard/chatbots/create/websites'
    | '/dashboard/knowledge-base/create/files'
    | '/dashboard/knowledge-base/create/knowledge'
    | '/dashboard/knowledge-base/create/text'
    | '/dashboard/knowledge-base/create/websites'
    | '/dashboard/chatbots/$id/'
    | '/dashboard/chatbots/create/'
    | '/dashboard/knowledge-base/create/'
    | '/dashboard/chatbots/$id/settings/ai'
    | '/dashboard/chatbots/$id/settings/chat-interface'
    | '/dashboard/chatbots/$id/settings/general'
    | '/dashboard/chatbots/$id/settings/security'
    | '/dashboard/chatbots/$id/sources/files'
    | '/dashboard/chatbots/$id/sources/knowledge-bases'
    | '/dashboard/chatbots/$id/sources/text'
    | '/dashboard/chatbots/$id/sources/websites'
    | '/dashboard/chatbots/$id/settings/'
    | '/dashboard/chatbots/$id/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/chatbots'
    | '/dashboard/knowledge-base'
    | '/dashboard/usages'
    | '/dashboard/chatbots/demo'
    | '/dashboard/tenants/create'
    | '/auth/login'
    | '/auth/register'
    | '/auth/renew-password'
    | '/auth/reset-password'
    | '/auth/verify-email'
    | '/dashboard/settings/billing'
    | '/dashboard/settings/general'
    | '/dashboard/settings/members'
    | '/dashboard/settings/plans'
    | '/dashboard/settings/security'
    | '/dashboard/chatbots/$id/playground'
    | '/dashboard/chatbots/$id/widget'
    | '/dashboard/chatbots/create/files'
    | '/dashboard/chatbots/create/knowledge'
    | '/dashboard/chatbots/create/text'
    | '/dashboard/chatbots/create/websites'
    | '/dashboard/knowledge-base/create/files'
    | '/dashboard/knowledge-base/create/knowledge'
    | '/dashboard/knowledge-base/create/text'
    | '/dashboard/knowledge-base/create/websites'
    | '/dashboard/chatbots/$id'
    | '/dashboard/chatbots/create'
    | '/dashboard/knowledge-base/create'
    | '/dashboard/chatbots/$id/settings/ai'
    | '/dashboard/chatbots/$id/settings/chat-interface'
    | '/dashboard/chatbots/$id/settings/general'
    | '/dashboard/chatbots/$id/settings/security'
    | '/dashboard/chatbots/$id/sources/files'
    | '/dashboard/chatbots/$id/sources/knowledge-bases'
    | '/dashboard/chatbots/$id/sources/text'
    | '/dashboard/chatbots/$id/sources/websites'
    | '/dashboard/chatbots/$id/settings'
    | '/dashboard/chatbots/$id/sources'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dashboard'
    | '/dashboard/_layout'
    | '/dashboard/_layout/chatbots'
    | '/dashboard/_layout/knowledge-base'
    | '/dashboard/_layout/usages'
    | '/dashboard/chatbots/$id'
    | '/dashboard/chatbots/create'
    | '/dashboard/chatbots/demo'
    | '/dashboard/knowledge-base/create'
    | '/dashboard/tenants/create'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/renew-password/'
    | '/auth/reset-password/'
    | '/auth/verify-email/'
    | '/dashboard/_layout/'
    | '/dashboard/_layout/settings/billing'
    | '/dashboard/_layout/settings/general'
    | '/dashboard/_layout/settings/members'
    | '/dashboard/_layout/settings/plans'
    | '/dashboard/_layout/settings/security'
    | '/dashboard/chatbots/$id/playground'
    | '/dashboard/chatbots/$id/settings'
    | '/dashboard/chatbots/$id/widget'
    | '/dashboard/chatbots/create/files'
    | '/dashboard/chatbots/create/knowledge'
    | '/dashboard/chatbots/create/text'
    | '/dashboard/chatbots/create/websites'
    | '/dashboard/knowledge-base/create/files'
    | '/dashboard/knowledge-base/create/knowledge'
    | '/dashboard/knowledge-base/create/text'
    | '/dashboard/knowledge-base/create/websites'
    | '/dashboard/chatbots/$id/'
    | '/dashboard/chatbots/create/'
    | '/dashboard/knowledge-base/create/'
    | '/dashboard/chatbots/$id/settings/ai'
    | '/dashboard/chatbots/$id/settings/chat-interface'
    | '/dashboard/chatbots/$id/settings/general'
    | '/dashboard/chatbots/$id/settings/security'
    | '/dashboard/chatbots/$id/sources/files'
    | '/dashboard/chatbots/$id/sources/knowledge-bases'
    | '/dashboard/chatbots/$id/sources/text'
    | '/dashboard/chatbots/$id/sources/websites'
    | '/dashboard/chatbots/$id/settings/'
    | '/dashboard/chatbots/$id/sources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthRenewPasswordIndexRoute: typeof AuthRenewPasswordIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/_layout': {
      id: '/dashboard/_layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_layout/': {
      id: '/dashboard/_layout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardLayoutIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/renew-password/': {
      id: '/auth/renew-password/'
      path: '/auth/renew-password'
      fullPath: '/auth/renew-password'
      preLoaderRoute: typeof AuthRenewPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenants/create': {
      id: '/dashboard/tenants/create'
      path: '/tenants/create'
      fullPath: '/dashboard/tenants/create'
      preLoaderRoute: typeof DashboardTenantsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/knowledge-base/create': {
      id: '/dashboard/knowledge-base/create'
      path: '/knowledge-base/create'
      fullPath: '/dashboard/knowledge-base/create'
      preLoaderRoute: typeof DashboardKnowledgeBaseCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chatbots/demo': {
      id: '/dashboard/chatbots/demo'
      path: '/chatbots/demo'
      fullPath: '/dashboard/chatbots/demo'
      preLoaderRoute: typeof DashboardChatbotsDemoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chatbots/create': {
      id: '/dashboard/chatbots/create'
      path: '/chatbots/create'
      fullPath: '/dashboard/chatbots/create'
      preLoaderRoute: typeof DashboardChatbotsCreateRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chatbots/$id': {
      id: '/dashboard/chatbots/$id'
      path: '/chatbots/$id'
      fullPath: '/dashboard/chatbots/$id'
      preLoaderRoute: typeof DashboardChatbotsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_layout/usages': {
      id: '/dashboard/_layout/usages'
      path: '/usages'
      fullPath: '/dashboard/usages'
      preLoaderRoute: typeof DashboardLayoutUsagesRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/knowledge-base': {
      id: '/dashboard/_layout/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/dashboard/knowledge-base'
      preLoaderRoute: typeof DashboardLayoutKnowledgeBaseRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/chatbots': {
      id: '/dashboard/_layout/chatbots'
      path: '/chatbots'
      fullPath: '/dashboard/chatbots'
      preLoaderRoute: typeof DashboardLayoutChatbotsRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/knowledge-base/create/': {
      id: '/dashboard/knowledge-base/create/'
      path: '/'
      fullPath: '/dashboard/knowledge-base/create/'
      preLoaderRoute: typeof DashboardKnowledgeBaseCreateIndexRouteImport
      parentRoute: typeof DashboardKnowledgeBaseCreateRoute
    }
    '/dashboard/chatbots/create/': {
      id: '/dashboard/chatbots/create/'
      path: '/'
      fullPath: '/dashboard/chatbots/create/'
      preLoaderRoute: typeof DashboardChatbotsCreateIndexRouteImport
      parentRoute: typeof DashboardChatbotsCreateRoute
    }
    '/dashboard/chatbots/$id/': {
      id: '/dashboard/chatbots/$id/'
      path: '/'
      fullPath: '/dashboard/chatbots/$id/'
      preLoaderRoute: typeof DashboardChatbotsIdIndexRouteImport
      parentRoute: typeof DashboardChatbotsIdRoute
    }
    '/dashboard/knowledge-base/create/websites': {
      id: '/dashboard/knowledge-base/create/websites'
      path: '/websites'
      fullPath: '/dashboard/knowledge-base/create/websites'
      preLoaderRoute: typeof DashboardKnowledgeBaseCreateWebsitesRouteImport
      parentRoute: typeof DashboardKnowledgeBaseCreateRoute
    }
    '/dashboard/knowledge-base/create/text': {
      id: '/dashboard/knowledge-base/create/text'
      path: '/text'
      fullPath: '/dashboard/knowledge-base/create/text'
      preLoaderRoute: typeof DashboardKnowledgeBaseCreateTextRouteImport
      parentRoute: typeof DashboardKnowledgeBaseCreateRoute
    }
    '/dashboard/knowledge-base/create/knowledge': {
      id: '/dashboard/knowledge-base/create/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge-base/create/knowledge'
      preLoaderRoute: typeof DashboardKnowledgeBaseCreateKnowledgeRouteImport
      parentRoute: typeof DashboardKnowledgeBaseCreateRoute
    }
    '/dashboard/knowledge-base/create/files': {
      id: '/dashboard/knowledge-base/create/files'
      path: '/files'
      fullPath: '/dashboard/knowledge-base/create/files'
      preLoaderRoute: typeof DashboardKnowledgeBaseCreateFilesRouteImport
      parentRoute: typeof DashboardKnowledgeBaseCreateRoute
    }
    '/dashboard/chatbots/create/websites': {
      id: '/dashboard/chatbots/create/websites'
      path: '/websites'
      fullPath: '/dashboard/chatbots/create/websites'
      preLoaderRoute: typeof DashboardChatbotsCreateWebsitesRouteImport
      parentRoute: typeof DashboardChatbotsCreateRoute
    }
    '/dashboard/chatbots/create/text': {
      id: '/dashboard/chatbots/create/text'
      path: '/text'
      fullPath: '/dashboard/chatbots/create/text'
      preLoaderRoute: typeof DashboardChatbotsCreateTextRouteImport
      parentRoute: typeof DashboardChatbotsCreateRoute
    }
    '/dashboard/chatbots/create/knowledge': {
      id: '/dashboard/chatbots/create/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/chatbots/create/knowledge'
      preLoaderRoute: typeof DashboardChatbotsCreateKnowledgeRouteImport
      parentRoute: typeof DashboardChatbotsCreateRoute
    }
    '/dashboard/chatbots/create/files': {
      id: '/dashboard/chatbots/create/files'
      path: '/files'
      fullPath: '/dashboard/chatbots/create/files'
      preLoaderRoute: typeof DashboardChatbotsCreateFilesRouteImport
      parentRoute: typeof DashboardChatbotsCreateRoute
    }
    '/dashboard/chatbots/$id/widget': {
      id: '/dashboard/chatbots/$id/widget'
      path: '/widget'
      fullPath: '/dashboard/chatbots/$id/widget'
      preLoaderRoute: typeof DashboardChatbotsIdWidgetRouteImport
      parentRoute: typeof DashboardChatbotsIdRoute
    }
    '/dashboard/chatbots/$id/settings': {
      id: '/dashboard/chatbots/$id/settings'
      path: '/settings'
      fullPath: '/dashboard/chatbots/$id/settings'
      preLoaderRoute: typeof DashboardChatbotsIdSettingsRouteImport
      parentRoute: typeof DashboardChatbotsIdRoute
    }
    '/dashboard/chatbots/$id/playground': {
      id: '/dashboard/chatbots/$id/playground'
      path: '/playground'
      fullPath: '/dashboard/chatbots/$id/playground'
      preLoaderRoute: typeof DashboardChatbotsIdPlaygroundRouteImport
      parentRoute: typeof DashboardChatbotsIdRoute
    }
    '/dashboard/_layout/settings/security': {
      id: '/dashboard/_layout/settings/security'
      path: '/settings/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardLayoutSettingsSecurityRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings/plans': {
      id: '/dashboard/_layout/settings/plans'
      path: '/settings/plans'
      fullPath: '/dashboard/settings/plans'
      preLoaderRoute: typeof DashboardLayoutSettingsPlansRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings/members': {
      id: '/dashboard/_layout/settings/members'
      path: '/settings/members'
      fullPath: '/dashboard/settings/members'
      preLoaderRoute: typeof DashboardLayoutSettingsMembersRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings/general': {
      id: '/dashboard/_layout/settings/general'
      path: '/settings/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof DashboardLayoutSettingsGeneralRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/_layout/settings/billing': {
      id: '/dashboard/_layout/settings/billing'
      path: '/settings/billing'
      fullPath: '/dashboard/settings/billing'
      preLoaderRoute: typeof DashboardLayoutSettingsBillingRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/chatbots/$id/sources/': {
      id: '/dashboard/chatbots/$id/sources/'
      path: '/sources'
      fullPath: '/dashboard/chatbots/$id/sources'
      preLoaderRoute: typeof DashboardChatbotsIdSourcesIndexRouteImport
      parentRoute: typeof DashboardChatbotsIdRoute
    }
    '/dashboard/chatbots/$id/settings/': {
      id: '/dashboard/chatbots/$id/settings/'
      path: '/'
      fullPath: '/dashboard/chatbots/$id/settings/'
      preLoaderRoute: typeof DashboardChatbotsIdSettingsIndexRouteImport
      parentRoute: typeof DashboardChatbotsIdSettingsRoute
    }
    '/dashboard/chatbots/$id/sources/websites': {
      id: '/dashboard/chatbots/$id/sources/websites'
      path: '/sources/websites'
      fullPath: '/dashboard/chatbots/$id/sources/websites'
      preLoaderRoute: typeof DashboardChatbotsIdSourcesWebsitesRouteImport
      parentRoute: typeof DashboardChatbotsIdRoute
    }
    '/dashboard/chatbots/$id/sources/text': {
      id: '/dashboard/chatbots/$id/sources/text'
      path: '/sources/text'
      fullPath: '/dashboard/chatbots/$id/sources/text'
      preLoaderRoute: typeof DashboardChatbotsIdSourcesTextRouteImport
      parentRoute: typeof DashboardChatbotsIdRoute
    }
    '/dashboard/chatbots/$id/sources/knowledge-bases': {
      id: '/dashboard/chatbots/$id/sources/knowledge-bases'
      path: '/sources/knowledge-bases'
      fullPath: '/dashboard/chatbots/$id/sources/knowledge-bases'
      preLoaderRoute: typeof DashboardChatbotsIdSourcesKnowledgeBasesRouteImport
      parentRoute: typeof DashboardChatbotsIdRoute
    }
    '/dashboard/chatbots/$id/sources/files': {
      id: '/dashboard/chatbots/$id/sources/files'
      path: '/sources/files'
      fullPath: '/dashboard/chatbots/$id/sources/files'
      preLoaderRoute: typeof DashboardChatbotsIdSourcesFilesRouteImport
      parentRoute: typeof DashboardChatbotsIdRoute
    }
    '/dashboard/chatbots/$id/settings/security': {
      id: '/dashboard/chatbots/$id/settings/security'
      path: '/security'
      fullPath: '/dashboard/chatbots/$id/settings/security'
      preLoaderRoute: typeof DashboardChatbotsIdSettingsSecurityRouteImport
      parentRoute: typeof DashboardChatbotsIdSettingsRoute
    }
    '/dashboard/chatbots/$id/settings/general': {
      id: '/dashboard/chatbots/$id/settings/general'
      path: '/general'
      fullPath: '/dashboard/chatbots/$id/settings/general'
      preLoaderRoute: typeof DashboardChatbotsIdSettingsGeneralRouteImport
      parentRoute: typeof DashboardChatbotsIdSettingsRoute
    }
    '/dashboard/chatbots/$id/settings/chat-interface': {
      id: '/dashboard/chatbots/$id/settings/chat-interface'
      path: '/chat-interface'
      fullPath: '/dashboard/chatbots/$id/settings/chat-interface'
      preLoaderRoute: typeof DashboardChatbotsIdSettingsChatInterfaceRouteImport
      parentRoute: typeof DashboardChatbotsIdSettingsRoute
    }
    '/dashboard/chatbots/$id/settings/ai': {
      id: '/dashboard/chatbots/$id/settings/ai'
      path: '/ai'
      fullPath: '/dashboard/chatbots/$id/settings/ai'
      preLoaderRoute: typeof DashboardChatbotsIdSettingsAiRouteImport
      parentRoute: typeof DashboardChatbotsIdSettingsRoute
    }
  }
}

interface DashboardLayoutRouteChildren {
  DashboardLayoutChatbotsRoute: typeof DashboardLayoutChatbotsRoute
  DashboardLayoutKnowledgeBaseRoute: typeof DashboardLayoutKnowledgeBaseRoute
  DashboardLayoutUsagesRoute: typeof DashboardLayoutUsagesRoute
  DashboardLayoutIndexRoute: typeof DashboardLayoutIndexRoute
  DashboardLayoutSettingsBillingRoute: typeof DashboardLayoutSettingsBillingRoute
  DashboardLayoutSettingsGeneralRoute: typeof DashboardLayoutSettingsGeneralRoute
  DashboardLayoutSettingsMembersRoute: typeof DashboardLayoutSettingsMembersRoute
  DashboardLayoutSettingsPlansRoute: typeof DashboardLayoutSettingsPlansRoute
  DashboardLayoutSettingsSecurityRoute: typeof DashboardLayoutSettingsSecurityRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardLayoutChatbotsRoute: DashboardLayoutChatbotsRoute,
  DashboardLayoutKnowledgeBaseRoute: DashboardLayoutKnowledgeBaseRoute,
  DashboardLayoutUsagesRoute: DashboardLayoutUsagesRoute,
  DashboardLayoutIndexRoute: DashboardLayoutIndexRoute,
  DashboardLayoutSettingsBillingRoute: DashboardLayoutSettingsBillingRoute,
  DashboardLayoutSettingsGeneralRoute: DashboardLayoutSettingsGeneralRoute,
  DashboardLayoutSettingsMembersRoute: DashboardLayoutSettingsMembersRoute,
  DashboardLayoutSettingsPlansRoute: DashboardLayoutSettingsPlansRoute,
  DashboardLayoutSettingsSecurityRoute: DashboardLayoutSettingsSecurityRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

interface DashboardChatbotsIdSettingsRouteChildren {
  DashboardChatbotsIdSettingsAiRoute: typeof DashboardChatbotsIdSettingsAiRoute
  DashboardChatbotsIdSettingsChatInterfaceRoute: typeof DashboardChatbotsIdSettingsChatInterfaceRoute
  DashboardChatbotsIdSettingsGeneralRoute: typeof DashboardChatbotsIdSettingsGeneralRoute
  DashboardChatbotsIdSettingsSecurityRoute: typeof DashboardChatbotsIdSettingsSecurityRoute
  DashboardChatbotsIdSettingsIndexRoute: typeof DashboardChatbotsIdSettingsIndexRoute
}

const DashboardChatbotsIdSettingsRouteChildren: DashboardChatbotsIdSettingsRouteChildren =
  {
    DashboardChatbotsIdSettingsAiRoute: DashboardChatbotsIdSettingsAiRoute,
    DashboardChatbotsIdSettingsChatInterfaceRoute:
      DashboardChatbotsIdSettingsChatInterfaceRoute,
    DashboardChatbotsIdSettingsGeneralRoute:
      DashboardChatbotsIdSettingsGeneralRoute,
    DashboardChatbotsIdSettingsSecurityRoute:
      DashboardChatbotsIdSettingsSecurityRoute,
    DashboardChatbotsIdSettingsIndexRoute:
      DashboardChatbotsIdSettingsIndexRoute,
  }

const DashboardChatbotsIdSettingsRouteWithChildren =
  DashboardChatbotsIdSettingsRoute._addFileChildren(
    DashboardChatbotsIdSettingsRouteChildren,
  )

interface DashboardChatbotsIdRouteChildren {
  DashboardChatbotsIdPlaygroundRoute: typeof DashboardChatbotsIdPlaygroundRoute
  DashboardChatbotsIdSettingsRoute: typeof DashboardChatbotsIdSettingsRouteWithChildren
  DashboardChatbotsIdWidgetRoute: typeof DashboardChatbotsIdWidgetRoute
  DashboardChatbotsIdIndexRoute: typeof DashboardChatbotsIdIndexRoute
  DashboardChatbotsIdSourcesFilesRoute: typeof DashboardChatbotsIdSourcesFilesRoute
  DashboardChatbotsIdSourcesKnowledgeBasesRoute: typeof DashboardChatbotsIdSourcesKnowledgeBasesRoute
  DashboardChatbotsIdSourcesTextRoute: typeof DashboardChatbotsIdSourcesTextRoute
  DashboardChatbotsIdSourcesWebsitesRoute: typeof DashboardChatbotsIdSourcesWebsitesRoute
  DashboardChatbotsIdSourcesIndexRoute: typeof DashboardChatbotsIdSourcesIndexRoute
}

const DashboardChatbotsIdRouteChildren: DashboardChatbotsIdRouteChildren = {
  DashboardChatbotsIdPlaygroundRoute: DashboardChatbotsIdPlaygroundRoute,
  DashboardChatbotsIdSettingsRoute:
    DashboardChatbotsIdSettingsRouteWithChildren,
  DashboardChatbotsIdWidgetRoute: DashboardChatbotsIdWidgetRoute,
  DashboardChatbotsIdIndexRoute: DashboardChatbotsIdIndexRoute,
  DashboardChatbotsIdSourcesFilesRoute: DashboardChatbotsIdSourcesFilesRoute,
  DashboardChatbotsIdSourcesKnowledgeBasesRoute:
    DashboardChatbotsIdSourcesKnowledgeBasesRoute,
  DashboardChatbotsIdSourcesTextRoute: DashboardChatbotsIdSourcesTextRoute,
  DashboardChatbotsIdSourcesWebsitesRoute:
    DashboardChatbotsIdSourcesWebsitesRoute,
  DashboardChatbotsIdSourcesIndexRoute: DashboardChatbotsIdSourcesIndexRoute,
}

const DashboardChatbotsIdRouteWithChildren =
  DashboardChatbotsIdRoute._addFileChildren(DashboardChatbotsIdRouteChildren)

interface DashboardChatbotsCreateRouteChildren {
  DashboardChatbotsCreateFilesRoute: typeof DashboardChatbotsCreateFilesRoute
  DashboardChatbotsCreateKnowledgeRoute: typeof DashboardChatbotsCreateKnowledgeRoute
  DashboardChatbotsCreateTextRoute: typeof DashboardChatbotsCreateTextRoute
  DashboardChatbotsCreateWebsitesRoute: typeof DashboardChatbotsCreateWebsitesRoute
  DashboardChatbotsCreateIndexRoute: typeof DashboardChatbotsCreateIndexRoute
}

const DashboardChatbotsCreateRouteChildren: DashboardChatbotsCreateRouteChildren =
  {
    DashboardChatbotsCreateFilesRoute: DashboardChatbotsCreateFilesRoute,
    DashboardChatbotsCreateKnowledgeRoute:
      DashboardChatbotsCreateKnowledgeRoute,
    DashboardChatbotsCreateTextRoute: DashboardChatbotsCreateTextRoute,
    DashboardChatbotsCreateWebsitesRoute: DashboardChatbotsCreateWebsitesRoute,
    DashboardChatbotsCreateIndexRoute: DashboardChatbotsCreateIndexRoute,
  }

const DashboardChatbotsCreateRouteWithChildren =
  DashboardChatbotsCreateRoute._addFileChildren(
    DashboardChatbotsCreateRouteChildren,
  )

interface DashboardKnowledgeBaseCreateRouteChildren {
  DashboardKnowledgeBaseCreateFilesRoute: typeof DashboardKnowledgeBaseCreateFilesRoute
  DashboardKnowledgeBaseCreateKnowledgeRoute: typeof DashboardKnowledgeBaseCreateKnowledgeRoute
  DashboardKnowledgeBaseCreateTextRoute: typeof DashboardKnowledgeBaseCreateTextRoute
  DashboardKnowledgeBaseCreateWebsitesRoute: typeof DashboardKnowledgeBaseCreateWebsitesRoute
  DashboardKnowledgeBaseCreateIndexRoute: typeof DashboardKnowledgeBaseCreateIndexRoute
}

const DashboardKnowledgeBaseCreateRouteChildren: DashboardKnowledgeBaseCreateRouteChildren =
  {
    DashboardKnowledgeBaseCreateFilesRoute:
      DashboardKnowledgeBaseCreateFilesRoute,
    DashboardKnowledgeBaseCreateKnowledgeRoute:
      DashboardKnowledgeBaseCreateKnowledgeRoute,
    DashboardKnowledgeBaseCreateTextRoute:
      DashboardKnowledgeBaseCreateTextRoute,
    DashboardKnowledgeBaseCreateWebsitesRoute:
      DashboardKnowledgeBaseCreateWebsitesRoute,
    DashboardKnowledgeBaseCreateIndexRoute:
      DashboardKnowledgeBaseCreateIndexRoute,
  }

const DashboardKnowledgeBaseCreateRouteWithChildren =
  DashboardKnowledgeBaseCreateRoute._addFileChildren(
    DashboardKnowledgeBaseCreateRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  DashboardChatbotsIdRoute: typeof DashboardChatbotsIdRouteWithChildren
  DashboardChatbotsCreateRoute: typeof DashboardChatbotsCreateRouteWithChildren
  DashboardChatbotsDemoRoute: typeof DashboardChatbotsDemoRoute
  DashboardKnowledgeBaseCreateRoute: typeof DashboardKnowledgeBaseCreateRouteWithChildren
  DashboardTenantsCreateRoute: typeof DashboardTenantsCreateRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  DashboardChatbotsIdRoute: DashboardChatbotsIdRouteWithChildren,
  DashboardChatbotsCreateRoute: DashboardChatbotsCreateRouteWithChildren,
  DashboardChatbotsDemoRoute: DashboardChatbotsDemoRoute,
  DashboardKnowledgeBaseCreateRoute:
    DashboardKnowledgeBaseCreateRouteWithChildren,
  DashboardTenantsCreateRoute: DashboardTenantsCreateRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthRenewPasswordIndexRoute: AuthRenewPasswordIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
